name: 'gg-ping-health-check'
description: 'Ping web service health check'
inputs:
  health_check_url:
    description: 'Web service health check URL'
    required: true
  contains:
    description: 'Expected message'
    required: false
  retry_delay_in_seconds:
    description: 'Retry delay in seconds'
    required: false
  max_attempts:
    description: 'Max number of attempts'
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
        docker run --rm \
          -e In__HealthCheckUrl="${{ inputs.health_check_url }}" \
          -e In__ContainedMessage="${{ inputs.contains }}" \
          -e In__RetryDelayInSeconds="${{ inputs.retry_delay_in_seconds }}" \
          -e In__MaxAttempts="${{ inputs.max_attempts }}" \
          ghcr.io/garagegroup/gg-ping-health-check:latest
      shell: bash
