name: Build and push docker image to Github Container Registry

on:
  page_build:
  release:
    types:
      - created

jobs:
  build-and-push-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Add Garage Group NuGet Source
        run: >
          dotnet nuget add source ${{ vars.GG_NUGET_SOURCE_URL }}
          -n garage
          -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
          -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
          --store-password-in-clear-text

      - name: Publish Console.csproj
        run: dotnet publish ./src/*/Console.csproj -c Release -o './publish'

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: |
            ghcr.io/garagegroup/gg-ping-health-check:${{ steps.vars.outputs.tag }}
            ghcr.io/garagegroup/gg-ping-health-check:latest
          push: true
